### PR TITLE
Merge pull request #1 from Naveen112001/day-1

### PR DESCRIPTION
**Pull request by Naveen112001**
This branch
1.Form 
2.Change of Size  of page
3.Style.css
4.Background color
5.details

### CODE REVIEW

**Comment by santynaren** [comment]
why no file changes?

**Comment by Naveen112001** [comment]
> why no file changes?

i changed it but i down know why files not included in repository

**Comment by Naveen112001** [comment]
> why no file changes?

new branch show no changes because of some wrong option selection.

**Review by santynaren — COMMENTED** [review]
Looks good, but why have you files  with no code shown

**Pull request merged**
